[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reactants-docking"
version = "0.0.0"
description = "A script to dock reactants based on their electrophilic and nucleophilic properties."
authors = [
    { name = "Laust Rask", email = "lauras@dtu.dk" }
]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "geatpy",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "isort",
    "mypy",
    "pre-commit",
]